# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.9837, 0.2775, 0.5159, 0.5469, 0.3959, 0.2612, 0.2903],
        [0.1566, 0.8284, 0.6786, 0.7635, 0.9594, 0.3235, 0.9007],
        [0.2030, 0.6863, 0.5441, 0.5443, 0.9723, 0.1883, 0.5481],
        [0.4166, 0.0264, 0.6346, 0.4097, 0.6017, 0.1940, 0.2847],
        [0.0801, 0.1353, 0.6561, 0.8884, 0.2512, 0.8549, 0.0486],
        [0.0714, 0.7260, 0.7395, 0.6268, 0.4378, 0.1169, 0.6901],
        [0.8377, 0.6773, 0.2267, 0.1090, 0.8215, 0.5860, 0.7704]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)
print(random_tensor_2)

# Perform matrix multiplication
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[0.4908, 0.8426, 0.5373, 0.7562, 0.2422, 0.4582, 0.2527]])


tensor([[1.6963],
        [2.3250],
        [1.8421],
        [1.1841],
        [1.6425],
        [1.8521],
        [1.8482]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
random_tensor_A = torch.rand(7, 7)
random_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(random_tensor_A, random_tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
random_tensor_A = torch.rand((2, 3), device='cpu')
random_tensor_B = torch.rand((2, 3), device='cpu')
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
matrix_mult = torch.matmul(random_tensor_A, random_tensor_B.T)
print(matrix_mult)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
minimum = matrix_mult.min()
print(f'Minimum: {minimum}')

# Find min
maximum = matrix_mult.max()
print(f'Maximum: {maximum}')

Minimum: 0.3647301495075226
Maximum: 0.5617256760597229


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
min_index = torch.argmin(matrix_mult)
print(f'Minimum Index: {min_index}')

# Find arg min
max_index = torch.argmax(matrix_mult)
print(f'Maximum Index: {max_index}')

Minimum Index: 0
Maximum Index: 3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
new_random_tensor = torch.squeeze(random_tensor)

# Print out tensors and their shapes
print(f'Random Tensor: \n{random_tensor}')
print(f'Size of Random Tensor: {random_tensor.size()}')
print(f'New Random Tensor: \n{new_random_tensor}')
print(f'Size of New Random Tensor: {new_random_tensor.size()}')

Random Tensor: 
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Size of Random Tensor: torch.Size([1, 1, 1, 10])
New Random Tensor: 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Size of New Random Tensor: torch.Size([10])
