## 00. PyTorch Fundamentals

In [ ]:
# Import libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu128


## Introduction to Tensors
### Types of Tensors
PyTorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html


In [ ]:
# Scalar (0D tensor)
scalar = torch.tensor(7)
print(scalar)
print(f'Dimension of scalar: {scalar.ndim}')
print(f'Shape of scalar: {scalar.shape}')

tensor(7)
Dimension of scalar: 0
Shape of scalar: torch.Size([])


In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector (1D tensor)
vector = torch.tensor([7, 7])
print(vector)
print(f'Dimension of vector: {vector.ndim}')
print(f'Shape of vector: {vector.shape}')

tensor([7, 7])
Dimension of vector: 1
Shape of vector: torch.Size([2])


In [ ]:
# MATRIX (2D tensor)
MATRIX = torch.tensor([[7, 8], [9, 10]])
print(MATRIX)
print(f'Dimension of matrix: {MATRIX.ndim}')
print(f'Shape of matrix: {MATRIX.shape}')

tensor([[ 7,  8],
        [ 9, 10]])
Dimension of matrix: 2
Shape of matrix: torch.Size([2, 2])


In [ ]:
### Access data in the MATRIX ###
# Obtain row 1 of the MATRIX
print(MATRIX[0])

# Obtain row 2 of the MATRIX
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [ ]:
# TENSOR (3D tensor)
TENSOR = torch.tensor([[[1, 2, 3], [6, 5, 9]], [[2, 3, 4], [0, 9, 8]], [[29, 8, 7], [1, 2, 9]]])
print(TENSOR)
print(f'Dimension of tensor: {TENSOR.ndim}')
print(f'Shape of tensor: {TENSOR.shape}')


tensor([[[ 1,  2,  3],
         [ 6,  5,  9]],

        [[ 2,  3,  4],
         [ 0,  9,  8]],

        [[29,  8,  7],
         [ 1,  2,  9]]])
Dimension of tensor: 3
Shape of tensor: torch.Size([3, 2, 3])


In [ ]:
# Obtain the second batch of the TENSOR
TENSOR[2]

tensor([[29,  8,  7],
        [ 1,  2,  9]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

In [ ]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8501, 0.7839, 0.3998, 0.1197],
        [0.7902, 0.6824, 0.3763, 0.6267],
        [0.6431, 0.9620, 0.8541, 0.3771]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
print(f'Shape of image size tensor: {random_image_size_tensor.shape}, Size of image size tensor: {random_image_size_tensor.ndim}')

Shape of image size tensor: torch.Size([3, 224, 224]), Size of image size tensor: 3


### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Multiply the tensor of 0s by a random tensor
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
print(ones)
print(f'Datatype of tensor of all ones: {ones.dtype}')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Datatype of tensor of all ones: torch.float32


### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange() to generate a tensor of increasing increment
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating zeros-like tensors
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Creating ones-like tensors
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # What datatype is the tensor (e.g. float32 or float16)
                               device = None, # What device is your tensor on
                               requires_grad = False) # Wheter or not to track gradients with the tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# Obtain the datatype of the float_32_tensor
print(f'Datatype of float_32_tensor: {float_32_tensor.dtype}')

Datatype of float_32_tensor: torch.float32


In [ ]:
# Convert the datatype of the float_32_tensor to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Multiply two tensors of different datatypes
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Long (int_64) tensor
int_64_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
print(int_64_tensor)
print(f'Datatype of int_64_tensor: {int_64_tensor.dtype}')

tensor([3, 6, 9])
Datatype of int_64_tensor: torch.int64


### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7864, 0.3718, 0.3875, 0.0468],
        [0.8688, 0.4362, 0.6291, 0.0379],
        [0.5880, 0.2749, 0.2949, 0.0950]])

In [ ]:
# Find out the datatype, shape, and device of tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.7864, 0.3718, 0.3875, 0.0468],
        [0.8688, 0.4362, 0.6291, 0.0379],
        [0.5880, 0.2749, 0.2949, 0.0950]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
# Create another random tensor
other_tensor = torch.rand(size = (4, 3), dtype = torch.float32, device = 'cuda')
other_tensor

tensor([[0.8157, 0.5143, 0.1759],
        [0.2933, 0.4736, 0.5112],
        [0.3792, 0.7105, 0.2037],
        [0.4462, 0.8736, 0.1503]], device='cuda:0')

In [ ]:
# Find out the datatype, shape, and device of second tensor
print(f'Datatype of tensor: {other_tensor.dtype}')
print(f'Shape of tensor: {other_tensor.shape}')
print(f'Device of tensor: {other_tensor.device}')

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 3])
Device of tensor: cuda:0


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
# Matrix Multiplication of two arrays of dimensions (3,2) and (2,3)
torch.matmul(torch.rand(3,2), torch.rand(2, 3))

tensor([[0.2459, 0.1026, 0.2044],
        [0.8273, 0.2739, 0.4249],
        [0.8476, 0.3201, 0.5807]])

In [ ]:
# Element-wise Multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication between two equal tensors
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
### Compare the time between using PyTorch's matrix multiplication and matrix multiplication through loops ###
# Time of matrix multiplication through loops
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.23 ms, sys: 37 µs, total: 1.27 ms
Wall time: 1.08 ms


In [ ]:
# Time of matrix multiplcation using PyTorch's matrix multiplication function
%%time
torch.matmul(tensor, tensor)

CPU times: user 159 µs, sys: 864 µs, total: 1.02 ms
Wall time: 8.86 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Define two tensors and print out their respective shapes
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
print(f'Shape of tensor_A: {tensor_A.shape}')
print(f'Shape of tensor_B: {tensor_B.shape}')

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_B: torch.Size([3, 2])


To fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose

A **transpose** switches the axes or dimensions of a given tensor


In [ ]:
# Print the original tensor_B and its shape
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# Print the transposed tensor_B and its shape
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation between tensor_B and tensor_A works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
# Define a random tensor
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin(x) -> returns index position of target tensor where the minimum value occurs
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
# Find the minimum value in the tensor using index from argmin(x)
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

In [ ]:
# Find the maximum value in the tensor using index from argmax(x)
x[9]

tensor(91)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Initialize a random tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension ushing reshape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view of the original tensor
z = x.view(1, 9)
print(f'Z_array: {z}')
print(f'Z_array shape: {z.shape}')

# Note: Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
print(f'Z_array: {z}')
print(f'X_array: {x}')

Z_array: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Z_array shape: torch.Size([1, 9])
Z_array: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
X_array: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0 -> 1, 1-> 2, 2-> 0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Index on the most inner bracket (last dimension)
x[0][2][2], x[:, 2, 2]

(tensor(9), tensor([9]))

In [ ]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

In [ ]:
# Use ':' to select 'all' of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor conversion
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9338, 0.3713, 0.5876, 0.1033],
        [0.5257, 0.5555, 0.8780, 0.5137],
        [0.8226, 0.6133, 0.1298, 0.6652]])
tensor([[0.8822, 0.9837, 0.4020, 0.2844],
        [0.0440, 0.0891, 0.2216, 0.8140],
        [0.7724, 0.6436, 0.2988, 0.0981]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# Create two random but reproducible tensors using a random seed
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3, PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-[ractices

E.g. run on GPU if avaliable, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Print the tensor and its device
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if avaliable)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])